In [1]:
import numpy as np
import gym 
import random 
import time
from IPython.display import clear_output

In [19]:
env = gym.make("FrozenLake-v0")

In [21]:
action_space_size= env.action_space.n
state_space_size = env.observation_space.n

q_table=np.zeros((state_space_size, action_space_size))
print(Qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [32]:
num_episodes = 100000
max_steps_per_episode = 100
learning_rate = 0.01
discount_rate=0.99

exploration_rate=1
max_exploration_rate = 1
min_exploration_rate=0.01
exploration_decay_rate=0.01


In [33]:
rewards_all_episodes = []

for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        # Update Q-table
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        state = new_state
        rewards_current_episode += reward
        if done== True:
                     break
                             
                             
        # Exploration rate decay
        exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
        # Add new reward
    rewards_all_episodes.append(rewards_current_episode)

# Calculate and print the average reward per thousand episodes
rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000                     
print("********Average reward per thousand episodes********\n")
for r in rewards_per_thosand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000


********Average reward per thousand episodes********

1000 :  0.47300000000000036
2000 :  0.6000000000000004
3000 :  0.6170000000000004
4000 :  0.6390000000000005
5000 :  0.6180000000000004
6000 :  0.5890000000000004
7000 :  0.6110000000000004
8000 :  0.5970000000000004
9000 :  0.6440000000000005
10000 :  0.6500000000000005
11000 :  0.6550000000000005
12000 :  0.6670000000000005
13000 :  0.6300000000000004
14000 :  0.6500000000000005
15000 :  0.6200000000000004
16000 :  0.6460000000000005
17000 :  0.6440000000000005
18000 :  0.6600000000000005
19000 :  0.6500000000000005
20000 :  0.6470000000000005
21000 :  0.6430000000000005
22000 :  0.6460000000000005
23000 :  0.6740000000000005
24000 :  0.6650000000000005
25000 :  0.6590000000000005
26000 :  0.6410000000000005
27000 :  0.6450000000000005
28000 :  0.6510000000000005
29000 :  0.6300000000000004
30000 :  0.6550000000000005
31000 :  0.6550000000000005
32000 :  0.6570000000000005
33000 :  0.6490000000000005
34000 :  0.6430000000000005
35

In [34]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)



********Q-table********

[[0.52620468 0.43024998 0.41968522 0.41809167]
 [0.27445867 0.1370572  0.05894202 0.14799059]
 [0.09761258 0.20432057 0.0887901  0.11335825]
 [0.03819595 0.09706396 0.01472898 0.04356371]
 [0.54625195 0.33800216 0.36415169 0.33613751]
 [0.         0.         0.         0.        ]
 [0.28083574 0.14856554 0.19447755 0.05145972]
 [0.         0.         0.         0.        ]
 [0.37216787 0.3897832  0.37644921 0.58339538]
 [0.46599736 0.62720615 0.43978214 0.37138193]
 [0.60099594 0.40645135 0.40320466 0.28707938]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.4427068  0.49435794 0.74471679 0.47932726]
 [0.71696371 0.87207702 0.79263804 0.76138376]
 [0.         0.         0.         0.        ]]


In [35]:
for episode in range(2):
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):        
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])        
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
            clear_output(wait=True)
            break  
        
        state = new_state
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
****You fell through a hole!****
